FROM alpine:3.19

RUN apk add --no-cache \
    dovecot \
    dovecot-pop3d \
    openssl \
    netcat-openbsd

RUN addgroup -g 1000 vmail && \
    adduser -D -u 1000 -G vmail -h /srv/vmail vmail

RUN mkdir -p /srv/vmail /etc/dovecot/ssl /run/dovecot && \
    chown -R vmail:vmail /srv/vmail

COPY --chmod=755 startup.sh /startup.sh

EXPOSE 143 993 110 995

ENTRYPOINT ["/startup.sh"]
